name: Molecule Test

on:
  push:
    branches:
      - Jchinmay654

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['centos7', 'debian10']
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install molecule[docker] ansible
          sudo systemctl start docker
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install ansible.posix
      - name: Molecule Test
        run: |
          cd ansible-role
          molecule test
        env: 
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
