name: Molecule Test

on:
  pull_request:
    branches:
      - main

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install molecule[docker] ansible
          sudo systemctl start docker
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install ansible.posix

      - name: molecule Test
        run: |
          # Get the name of the branch associated with the pull request
          branch_name="${{ github.event.pull_request.head.ref }}"

          # Clone the repository and search for the roles directory
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename "${{ github.repository }}" .git)
          role_dir="$(find . -type d -name roles)"

          # Navigate to the role directory and run molecule test
          cd "${role_dir}"
          cd "${branch_name}"
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
