name: Molecule Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['centos7', 'debian10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install molecule[docker] ansible
          sudo systemctl start docker
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install ansible.posix
      
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Run Molecule Test
        if: ${{ github.event_name == 'pull_request' }}
        uses: monolithprojects/action-molecule@v1.4.1
        with:
          molecule_command: 'test'
          scenario_name: '${{ github.event.pull_request.head.repo.name }}'
          molecule_extra_args: '-- --destroy never'
          molecule_platform: ${{ matrix.platform }}
          molecule_driver: docker
          molecule_lint: false
        env:
          MOLECULE_NO_LOG: 'false'
          MOLECULE_NO_ANSI: 'false'
