name: Molecule Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['centos7', 'debian10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install molecule[docker] ansible
          sudo systemctl start docker
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install ansible.posix
      
      - name: Run Molecule Test
        if: github.event_name == 'pull_request'
        run: |
          echo "Github Workspace: ${github.workspace}"
          echo "Github Event Pull Request Head Repo Name: ${github.event.pull_request.head.repo.name}"
          for dir in $(find ${{ github.workspace }} -type d -name "${{ inputs.directory-path }}"); do
            cd $dir && molecule test
          done
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        working-directory: ${{ github.event.pull_request.head.repo.name }}
        inputs:
          directory-path:
            description: 'Directory path to run Molecule tests'
            required: true
