name: Molecule Test

on:
  pull_request:
    branches:
      - main

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['centos7', 'debian10']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install molecule[docker] ansible
          sudo systemctl start docker
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install ansible.posix

        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

      - name: Run Molecule Test
        uses: monolithprojects/action-molecule@v1.4.1
        with:
          path: "roles/${{ github.repository_name }}/molecule/${{ github.head_ref }}"
          Molecule_Command: "test"
          Converge_Extra_Args: ""
          Scenario: "default"
          OS: "${{ matrix.platform }}"
          Tag: ""
        env:
          GITHUB_REF: ${{ github.head_ref }}
