name: Molecule Testtttttttttttttttt

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install molecule[docker] ansible
          sudo systemctl start docker
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install ansible.posix
      
      - name: Get Repository Directories
        id: repo-dirs
        uses: gr2m/get-repository-directories@v1.x
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          top_level_only: false
      
      - name: Run Molecule Tests
        run: |
          for dir in ${{ steps.repo-dirs.outputs.relative_paths }}; do
            if [ -d "${dir}/meta" ]; then
              role_dir="$(dirname "${dir}")"
              cd "${role_dir}" && molecule test
            fi
          done
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        if: github.event_name == 'pull_request'
